version: '3.9'

services:
  api:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: sh -c "celery -A app.workers.celery_app.celery_app worker -l info"
    depends_on:
      - api
      - redis

  beat:
    build: .
    command: sh -c "celery -A app.workers.celery_app.celery_app beat -l info"
    depends_on:
      - worker

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:


