version: '3.9'

services:
  api:
    build: .
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks: [web]
    depends_on: [postgres, redis]

  worker:
    build: .
    env_file: .env
    command: celery -A app.workers.celery_app.celery_app worker -l info
    networks: [web]
    depends_on: [redis]

  beat:
    build: .
    env_file: .env
    command: celery -A app.workers.celery_app.celery_app beat -l info
    networks: [web]
    depends_on: [worker]

  postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [web]

  redis:
    image: redis:7
    networks: [web]

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [api]
    networks: [web]

volumes:
  pgdata:

networks:
  web:


